import { ImageSourcePropType } from 'react-native';

export const Icons = {
  trash: require('./ic_trash.png'),
  eye_open: require('./ic_eye_open.png'),
  eye_close: require('./ic_eye_close.png'),
  gg: require('./ic_gg.png'),
  fb: require('./ic_fb.png'),
  smiley: require('./ic_smiley.png'),
  refresh: require('./ic_refresh.png'),
  arrow_right: require('./ic_arrow_right.png'),
  arrow_left: require('./ic_arrow_left.png'),
  xcircle: require('./ic_xcircle.png'),
  dashboard: require('./ic_dashboard.png'),
  person: require('./ic_person.png'),
  project: require('./ic_project.png'),
  settings: require('./ic_settings.png'),
  search: require('./ic_search.png'),
  menu: require('./ic_menu.png'),
  notification: require('./ic_notification.png'),
  plus: require('./ic_plus.png'),
  arrow_lineup: require('./ic_arrow_lineup.png'),
  more: require('./ic_more.png'),
  foward: require('./ic_foward.png'),
  backward: require('./ic_backward.png'),
  delete: require('./ic_delete.png'),
  arrowDown: require('./ic_arrow_down.png'),
  edit: require('./ic_edit.png'),
};
